import os
import logging
import json
import datetime
from typing import Dict, Any, List, Optional

# Word
from docx import Document
from docx.shared import Inches, Pt

# Excel
import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

# PowerPoint
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt

# PDF
from pypdf import PdfReader, PdfWriter
import pdfplumber
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

logger = logging.getLogger(__name__)

class DocumentAutomationService:
    def __init__(self, output_dir: str = "data/generated_docs"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def _generate_filename(self, title: str, ext: str) -> str:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{title.replace(' ', '_')}_{timestamp}.{ext}"

    async def create_word_report(self, title: str, sections: List[Dict[str, str]]) -> str:
        """Creates a professional Word report."""
        doc = Document()
        doc.add_heading(title, 0)

        for section in sections:
            doc.add_heading(section.get("heading", "Section"), level=1)
            doc.add_paragraph(section.get("content", ""))

        filename = self._generate_filename(title, "docx")
        file_path = os.path.join(self.output_dir, filename)
        doc.save(file_path)
        return file_path

    async def create_excel_model(self, title: str, data: List[Dict[str, Any]]) -> str:
        """Creates a professional Excel model with formulas."""
        df = pd.DataFrame(data)
        filename = self._generate_filename(title, "xlsx")
        file_path = os.path.join(self.output_dir, filename)
        
        # Use pandas to write initial data
        df.to_excel(file_path, index=False, sheet_name="Data")
        
        # Use openpyxl for formatting and formulas
        wb = load_workbook(file_path)
        ws = wb.active
        
        # Add a summary row with formulas
        last_row = len(data) + 1
        summary_row = last_row + 2
        ws.cell(row=summary_row, column=1, value="TOTAL")
        
        # Assuming numeric columns start from B (2)
        for col in range(2, ws.max_column + 1):
            col_letter = ws.cell(row=1, column=col).column_letter
            ws.cell(row=summary_row, column=col, value=f"=SUM({col_letter}2:{col_letter}{last_row})")
            ws.cell(row=summary_row, column=col).font = Font(bold=True)
            
        wb.save(file_path)
        return file_path

    async def create_presentation(self, title: str, slides_content: List[Dict[str, Any]]) -> str:
        """Creates a professional PowerPoint presentation."""
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        title_shape.text = title
        subtitle_shape.text = f"Generated by PKY AI Assistant on {datetime.datetime.now().strftime('%Y-%m-%d')}"

        # Content Slides
        for s_content in slides_content:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = s_content.get("title", "Slide")
            
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.text = s_content.get("content", "")
            
            for bullet in s_content.get("bullets", []):
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 1

        filename = self._generate_filename(title, "pptx")
        file_path = os.path.join(self.output_dir, filename)
        prs.save(file_path)
        return file_path

    async def create_pdf_report(self, title: str, content: str) -> str:
        """Creates a basic PDF report using reportlab."""
        filename = self._generate_filename(title, "pdf")
        file_path = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(file_path, pagesize=letter)
        width, height = letter
        
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width/2, height - 100, title)
        
        c.setFont("Helvetica", 12)
        text_object = c.beginText(100, height - 150)
        
        # Simple line wrapping
        for line in content.split('\n'):
            text_object.textLine(line)
            
        c.drawText(text_object)
        c.showPage()
        c.save()
        return file_path

    async def parse_document(self, file_path: str) -> str:
        """Parses various document formats and returns text content."""
        ext = os.path.splitext(file_path)[1].lower()
        
        if ext == ".pdf":
            text = ""
            with pdfplumber.open(file_path) as pdf:
                for page in pdf.pages:
                    text += page.extract_text() + "\n"
            return text
        elif ext == ".docx":
            doc = Document(file_path)
            return "\n".join([p.text for p in doc.paragraphs])
        elif ext == ".pptx":
            prs = Presentation(file_path)
            text = []
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text"):
                        text.append(shape.text)
            return "\n".join(text)
        elif ext == ".xlsx":
            df = pd.read_excel(file_path)
            return df.to_string()
        else:
            with open(file_path, "r", encoding="utf-8") as f:
                return f.read()
