#!/bin/bash

# PKY AI Assistant Android Development Setup Script
# This script sets up the development environment for the PKY AI Assistant Android app

echo "Setting up PKY AI Assistant Android Development Environment..."

# Check for Android Studio
if ! command -v adb &> /dev/null; then
    echo "Warning: adb not found. Please install Android Studio and add it to your PATH."
fi

# Create local.properties if it doesn't exist
if [ ! -f "local.properties" ]; then
    echo "Creating local.properties..."
    cat > local.properties << EOF
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# Location of the android SDK. This is only used by Gradle.
sdk.dir=$ANDROID_HOME
EOF
fi

# Check if backend is running
echo "Checking backend connectivity..."
if curl -s http://localhost:8000/ > /dev/null; then
    echo "✓ Backend is running on http://localhost:8000"
else
    echo "✗ Backend is not running. Please start the PKY AI Assistant backend first:"
    echo "  cd 'pky-ai-backend' && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
fi

# Android emulator port forwarding
echo "Setting up port forwarding for Android emulator..."
adb forward tcp:8000 tcp:8000 2>/dev/null || echo "Note: Port forwarding requires a running emulator/device"

# Build the project
echo "Building the Android project..."
./gradlew buildDebug 2>/dev/null || echo "Build failed. Please check Android Studio setup."

echo ""
echo "Setup complete!"
echo "Next steps:"
echo "1. Open the project in Android Studio"
echo "2. Run the app on an emulator or physical device"
echo "3. Grant microphone permission when prompted"
echo "4. Update backendUrl in MainActivity.kt if needed"
echo ""
echo "For development:"
echo "  Backend URL (emulator): ws://10.0.2.2:8000/ws/voice"
echo "  Backend URL (physical): ws://<your-ip>:8000/ws/voice"